import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Header } from "@/Components/Header";

const releway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Explore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={releway.className}>
        <Header/>
        {children}</body>
    </html>
  );
}
